[workspace]
members = [
    "triton-vm",
    "triton-opcodes",
    "triton-profiler",
    "constraint-evaluation-generator",
]

[profile.test]
opt-level = 1

[profile.release]
lto = "thin"

[profile.bench]
lto = "thin"

[workspace.package]
version = "0.30.0"
edition = "2021"
authors = ["Triton Software AG"]
license = "Apache-2.0"
homepage = "https://triton-vm.org/"
repository = "https://github.com/TritonVM/triton-vm"
readme = "README.md"
documentation = "https://triton-vm.org/spec/"

[workspace.dependencies]
twenty-first = "0.30"
triton-opcodes = "0.30"
triton-profiler = "0.30"
itertools = "0.10"
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
anyhow = "1.0"
get-size = "0.1.3"
num-traits = "0.2"
rand = "0.8.5"
rand_core = "0.6.4"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
strum = "0.24.1"
strum_macros = "0.24.1"
proptest = "1.0"
criterion = { version = "0.5", features = ["html_reports"] }
bincode = "1.3"
rayon = "1.5"
ndarray = { version = "0.15", features = ["rayon"] }
nom = "7.1"
colored = "2.0"
unicode-width = "0.1.5"

[workspace.dependencies.cargo-husky]
version = "1.0"
default-features = false
features = ["precommit-hook", "run-cargo-clippy", "run-cargo-fmt"]
