[workspace]
members = ["triton-vm", "constraint-evaluation-generator"]
resolver = "2"

[profile.test]
opt-level = 1

[profile.release]
lto = "thin"

[profile.bench]
lto = "thin"

[workspace.package]
version = "0.33.0"
edition = "2021"
authors = ["Triton Software AG"]
license = "Apache-2.0"
homepage = "https://triton-vm.org/"
repository = "https://github.com/TritonVM/triton-vm"
readme = "README.md"
documentation = "https://triton-vm.org/spec/"

[workspace.dependencies]
anyhow = "1.0"
bincode = "1.3"
colored = "2.0"
criterion = { version = "0.5", features = ["html_reports"] }
get-size = "0.1.4"
itertools = "0.11"
lazy_static = "1.4"
ndarray = { version = "0.15", features = ["rayon"] }
nom = "7.1"
num-traits = "0.2"
prettyplease = "0.2"
proc-macro2 = "1.0"
proptest = "1.2"
quote = "1.0"
rand = "0.8.5"
rand_core = "0.6.4"
rayon = "1.7"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
strum = "0.25"
strum_macros = "0.25"
syn = "2.0"
twenty-first = "0.32"
unicode-width = "0.1"

[workspace.dependencies.cargo-husky]
version = "1.5"
default-features = false
features = ["precommit-hook", "run-cargo-clippy", "run-cargo-fmt"]
