[book]
authors = ["Triton Software AG"]
language = "en"
multilingual = false
src = "src"
title = "Triton VM"

[preprocessor.katex]

[output.linkcheck]
warning-policy = "ignore" # most latex will generate a warning

[output.html]
git-repository-url = "https://github.com/TritonVM/triton-vm/tree/master/specification"
additional-css = ["custom.css"]
