[package]
name = "triton-vm"
description = """
A virtual machine that comes with Algebraic Execution Tables (AET) and Arithmetic Intermediate Representations (AIR)
for use in combination with a STARK proof system to allow proving correct execution of arbitrary programs
in zero-knowledge.
"""
keywords = ["zero-knowledge", "STARK", "virtual-machine", "recursive"]
categories = ["cryptography", "mathematics"]

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
triton-opcodes.workspace = true
triton-profiler.workspace = true
twenty-first.workspace = true
itertools.workspace = true
quote.workspace = true
proc-macro2.workspace = true
anyhow.workspace = true
get-size.workspace = true
num-traits.workspace = true
rand.workspace = true
rand_core.workspace = true
serde.workspace = true
strum.workspace = true
strum_macros.workspace = true

bincode = "1.3"
rayon = "1.5"
ndarray = { version = "0.15", features = ["rayon"] }

[dev-dependencies]
proptest.workspace = true
criterion.workspace = true
cargo-husky.workspace = true

[[bench]]
name = "prove_halt"
harness = false

[[bench]]
name = "prove_fib_100"
harness = false

[[bench]]
name = "verify_halt"
harness = false

[[bench]]
name = "proof_size"
harness = false
