on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Rust

jobs:
  runner-matrix:
    name: Build, lint, test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Build constraints
        run: cargo run --bin constraint-evaluation-generator

      - name: Run fmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Run tests
        run: cargo test

      - name: Build benchmarks
        run: cargo bench --all-targets --no-run
