on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Rust

jobs:
  build:
    name: Build, lint, test and bench
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0, 2022-10-13

      - name: Install stable toolchain
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # v1.0.7, 2020-03-24
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build constraints
        run: make build-constraints

      - name: Build tests
        run: make build-tests

      - name: Build bench
        run: make build-bench

      - name: Run fmt
        run: make fmt-only

      - name: Run clippy
        run: make clippy-only

      - name: Run tests
        run: make test

      - name: Run benchmarks
        run: make bench